{% set name = "xcengine" %}
{% set version = "0.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xcube-dev/xcengine/archive/v{{ version }}.tar.gz
  sha256: 19f87c6f50bdfbf08c0b707e6906300ed82b8926ebf6ec8af7ace37891790b78

build:
  entry_points:
    - xcetool = xcengine.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=40.9.0
    - pip
  run:
    - python >={{ python_min }}
    - click
    - docker-py
    - ipython
    - nbconvert
    - nbformat
    - pystac
    - pyyaml
    - xarray
    - xcube

test:
  imports:
    - xcengine
  commands:
    # "pip check" omitted, since it expects a package named xcube-core
    - xcetool --help
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/xcube-dev/xcengine
  summary: Turn Jupyter notebooks into Application Packages
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - b-yogesh
    - forman
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
